name: auto merges

on:
  schedule:
  - cron: "25 15 * * *"
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
     
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@v0.13.0"
        env:
          GITHUB_TOKEN: "${{ secrets.ACTION_REPO }}"
          MERGE_RETRIES: "3"
          MERGE_RETRY_SLEEP: "5000"
