name: labels merge

on:
  schedule:
    - cron: "20 21 * * *"
  pull_request:
    types:
      - opened
      - labeled

jobs:
  add_labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-ecosystem/action-add-labels@v1.1.0
        with:
          github_token:  ${{ secrets.ACTION_TOKEN }}
          number: 57
          repo: ${{ github.repository }}
          labels: automerge
