name: label auto merge

on:
  schedule:
    - cron: "2 * * * *"
  pull_request:
    types: open

jobs:
  add_labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.github_token }}
          labels: automerge
