name: labels merge

on:
  schedule:
  - cron: "20/20 20 * * *"
  pull_request:
    types:
      - labeled
      - opened
      - reopened
      - synchronize

jobs:
  add_labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ github.event.pull_request.number }}
          repo: chrdek/vuejs-imggallery
          labels: automerge
