name: auto label

on:
  pull_request:
    branches: master
  schedule:
    - cron: "40/10 11 * * *"
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v3
      with:
    # The GITHUB_TOKEN secret
        repo-token: "{{ $secrets.GITHUB_TOKEN }}"
    # The path for the label configurations
        configuration-path: .github/workflows/label.yml
    # optional set to workflows/label.yml
    # Whether or not to remove labels when matching files are reverted
