# This is a basic workflow to help you get started with Actions

name: "Auto Labeler"
on:
 pull_request

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@main
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
