# auto labeling functionality for pulls.

name: "Auto Labeler"
on:
 pull_request_target

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@main
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
