# Basic workflow for security dependencies merge.
name: SEC MERGE

on:
  pull_request:
    branches: 
      - master
jobs: 
      merge_job: 
# Scheduling done via host, altern. via CronExpr: 0 0 22/10 * 5 *
        runs-on: self-hosted
        
# Merges on latest master, adds default message.
        steps: 
          - name: Pull requests direct merge with message
