name: stales check
on:
  schedule:
  - cron: "50/5 13 * * *"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'Issue pending'
        stale-pr-message: 'PR(s) pending'
        stale-issue-label: 'old-issue'
        stale-pr-label: 'old-pr'
