name: await-status-action

on:
  schedule:
  - cron: "15 10 * * *"

jobs:
  status-action:

    runs-on: ubuntu-latest

    steps:
    - uses: Sibz/await-status-action@v1.0.1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
